### ISSUE TITLE
[ERROR]: Message: no such element: Unable to locate element: 

### ISSUE THREAD

**Issue by Foluwa** [aahouzi/Instagram-Scraper-2021#5]
I encountered an error:

[ERROR]: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[2]/div/div/button[1]"}

(Session info: headless chrome=91.0.4472.106)

Any guide on how to resolve

**Comment by ghost** [comment]
Hi! thank you for pointing out the issue, u can try with the new version of my code, it's working just fine.
