### ISSUE TITLE
Proxy server options

### ISSUE THREAD

**Issue by yunhwankim2** [aahouzi/Instagram-Scraper-2021#7]
Hi. 
I tried to use the code, but it seems the line below generates "ProxyServerError: Can't connect to Browsermob-Proxy"

```
server = Server(proxy_path, options={"port": 8000})  # line 248 in insta_feed_scraper.py
```

I removed the "options={"port": 8000}" part, and it seems work fine so far. 
Just for your information.
Thank you.

**Comment by ghost** [comment]
Same here, u can create a pull request
